version: '3.9'
services:
  olx_scrap:
    build: .
    container_name: olx_scrap
    command: python -u app.py
    tty: true
    stdin_open: true
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    links:
      - db
  db:
    image: mongo:4.4.20-rc0-focal
    environment:
      - MONGO_INITDB_DATABASE=olx_db
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - ./db_backup:/data/db/
    ports:
      - 27017:27017
    tty: false
    stdin_open: false
